version: '3.8'
services:
  mlclient:
    build: ./machine_learning_client

    ports:
      - '1000:1000'

    depends_on:
      - db

  web_app:
    build: ./web_app
    ports:
      - "5001:5001"
    depends_on:
      - db
      - mlclient

  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
