version: '3.8'
services:
  machine_learning_client:
    build: ./machine_learning_client

    ports:
      - '1000:1000'
    networks:
      - app-network
    depends_on:
      - mongo

  web_app:
    build: ./web_app
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - mongo
      - machine_learning_client

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
