version: '3'

services:
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"

  web_app:
    build: ./web_app
    dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      FLASK_APP: web_app/app.py

  machine_learning_client:
    build: ./machine_learning_client
    dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
